name: flutter_auth_app
description: A simple to-do list app with Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# This is the main configuration section for Flutter-specific settings
flutter:

  # This key must be indented under 'flutter:'
  uses-material-design: true

  # This key must also be indented under 'flutter:'

# This key is at the root level, which is correct
flutter_native_splash:

  # The background color of your splash screen
  color: "#FFFFFF" # White

  # The path to your splash logo file
  image: assets/images/splash_logo.png

  # Configuration for Android 12+
  android_12:
    color: "#FFFFFF"
    image: assets/images/splash_logo.png

  # Configuration for the web splash screen
  web:
    color: "#FFFFFF"
    image: assets/images/splash_logo.png
