// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByUSMbQht3RJFidvEHMNSC1EM6AMWI6iA',
    appId: '1:963087425185:web:46e3408f79b69013cadae0',
    messagingSenderId: '963087425185',
    projectId: 'myapp-97fe6',
    authDomain: 'myapp-97fe6.firebaseapp.com',
    storageBucket: 'myapp-97fe6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5S8Inn4YJ1ClZE4f_AR2Rme3akz_YQBI',
    appId: '1:963087425185:android:d4c940e136e25c16cadae0',
    messagingSenderId: '963087425185',
    projectId: 'myapp-97fe6',
    storageBucket: 'myapp-97fe6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNeEHTHh_EtlKlwdwtC2CdMjt-DYuI8Qk',
    appId: '1:963087425185:ios:3649a11d4674078acadae0',
    messagingSenderId: '963087425185',
    projectId: 'myapp-97fe6',
    storageBucket: 'myapp-97fe6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNeEHTHh_EtlKlwdwtC2CdMjt-DYuI8Qk',
    appId: '1:963087425185:ios:3649a11d4674078acadae0',
    messagingSenderId: '963087425185',
    projectId: 'myapp-97fe6',
    storageBucket: 'myapp-97fe6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByUSMbQht3RJFidvEHMNSC1EM6AMWI6iA',
    appId: '1:963087425185:web:6b40238193f0f80ecadae0',
    messagingSenderId: '963087425185',
    projectId: 'myapp-97fe6',
    authDomain: 'myapp-97fe6.firebaseapp.com',
    storageBucket: 'myapp-97fe6.firebasestorage.app',
  );

}